<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CTSNJY30731" name="testscripts.scenario1.TC3" tests="1" failures="0" timestamp="16 Aug 2014 00:26:03 GMT" time="43.713" errors="1">
  <testcase name="runTC3" time="43.713" classname="testscripts.scenario1.TC3">
    <error type="java.lang.AssertionError" message="Login failed for valid user">
      <![CDATA[java.lang.AssertionError: Login failed for valid user
	at org.testng.Assert.fail(Assert.java:94)
	at supportlibraries.DriverScript.wrapUp(DriverScript.java:452)
	at supportlibraries.DriverScript.driveTestExecution(DriverScript.java:106)
	at testscripts.scenario1.TC3.runTC3(TC3.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
]]>
    </error>
  </testcase> <!-- runTC3 -->
</testsuite> <!-- testscripts.scenario1.TC3 -->
